project:
  type: website

website:
  title: "AHEAD Indicators | References"
  navbar:
    background: "#5544cc"
    left:
      - href: qmd/index.qmd
        text: Home
      - href: qmd/indicators.qmd
        text: Indicators
      - href: qmd/references.qmd
        text: References
  page-footer:
    background: "#5544cc"
    left: |
      Copyright 2025 Ahead | All Rights Reserved
    right:
      - href: https://github.com/
        icon: github
        aria-label: GitHub
      - href: https://www.linkedin.com/
        icon: linkedin
        aria-label: LinkedIn
    center: |
      The research leading to these results has received funding from the Horizon Europe Programme under the Marie Sk≈Çodowska-Curie grant agreement No 101183031. Views and opinions expressed are however those of the author(s) only and do not necessarily reflect those of the European Union. Neither the European Union nor the granting authority can be held responsible for them.

format:
  html:
    theme:
      light: [cosmo, scss/light-theme.scss]
    css: scss/styles.css
    toc: false
    minimal: false
    smooth-scroll: true
    




editor: visual

